baseURL: 'https://blog.kassiansun.com/'
languageCode: 'en-us'
title: 'Kassian Sun'
theme: 'PaperMod'
googleAnalytics: 'G-E9FSQ1R0HV'

languages:
  en:
    languageName: 'English'
    weight: 1
    menu:
      main:
        - name: About
          url: /about
